name: create-release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:

    runs-on: ubuntu-18.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download and extract latest miner-tools release
        run: |
          PMG_OPENCL_URL="https://github.com/tontechio/pow-miner-gpu/releases/latest/download/minertools-opencl-ubuntu-18.04-x86-64.tar.gz"
          PMG_CUDA_URL="https://github.com/tontechio/pow-miner-gpu/releases/latest/download/minertools-cuda-ubuntu-18.04-x86-64.tar.gz"
          wget -O minertools-opencl-ubuntu-18.04-x86-64.tar.gz $PMG_OPENCL_URL
          wget -O minertools-cuda-ubuntu-18.04-x86-64.tar.gz $PMG_CUDA_URL
          tar -xf minertools-opencl-ubuntu-18.04-x86-64.tar.gz -C ./assets/
          tar -xf minertools-cuda-ubuntu-18.04-x86-64.tar.gz -C ./assets/
          rm -f minertools-opencl-ubuntu-18.04-x86-64.tar.gz
          rm -f minertools-cuda-ubuntu-18.04-x86-64.tar.gz

      - name: Print minertools build version
        run: |
          echo "Release $RELEASE_VERSION"
          ./assets/lite-client -V
          ./assets/pow-miner-cuda -V
          ./assets/tonlib-cuda-cli -V
      #          ./assets/pow-miner-opencl -V
      #          ./assets/tonlib-opencl-cli -V

      - name: Save release version
        run: |
          echo "{\"version\":\"$RELEASE_VERSION\"}" > ./config/release.json

      - name: Download latest blockchain config
        run: |
          BLOCK_CHAIN_GC_URL="https://newton-blockchain.github.io/global.config.json"
          wget -O ./config/global.config.json $BLOCK_CHAIN_GC_URL

      - name: Define modes for files
        run: |
          chmod +x ./assets/pow-miner-opencl
          chmod +x ./assets/tonlib-opencl-cli
          chmod +x ./assets/pow-miner-cuda
          chmod +x ./assets/tonlib-cuda-cli
          chmod +x ./assets/lite-client

      - name: Prepare cuda assets
        run: |
          GENERAL="README.md ./config/global.config.json ./config/release.json ./h-config.sh ./h-manifest.conf ./h-run.sh ./h-stats.sh ./assets/tonminer.service"
          CUDA="./assets/lite-client ./assets/pow-miner-cuda ./assets/tonlib-cuda-cli"
          mkdir tonminer_cuda_hiveos_x86_64
          cp --parents $GENERAL $CUDA ./tonminer_cuda_hiveos_x86_64/
          tar -zcf tonminer_cuda_hiveos_x86_64-$RELEASE_VERSION.tar.gz ./tonminer_cuda_hiveos_x86_64

      - name: Opencl variable substitution
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "cuda"
          replace: "opencl"
          regex: false
          include: "**h-config.sh"

      - name: Prepare opencl assets
        run: |
          GENERAL="README.md ./config/global.config.json ./config/release.json ./h-config.sh ./h-manifest.conf ./h-run.sh ./h-stats.sh ./assets/tonminer.service"
          OPENCL="./assets/lite-client ./assets/pow-miner-opencl ./assets/tonlib-opencl-cli"
          mkdir tonminer_opencl_hiveos_x86_64
          cp --parents $GENERAL $OPENCL ./tonminer_opencl_hiveos_x86_64/
          tar -zcf tonminer_opencl_hiveos_x86_64-$RELEASE_VERSION.tar.gz ./tonminer_opencl_hiveos_x86_64

      - name: Packing
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: tonminer_*_hiveos_x86_64-*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare README.md
        run: |
          sed -e "s/{{RELEASE_VERSION}}/$RELEASE_VERSION/g" "./.github/README-TEMPLATE.md" > ./README.md

      - name: Get Branch
        run: |
          echo ${{ github.event.base_ref }}
          echo "BRANCH=$(echo ${{ github.event.base_ref }} | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Push README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-update README.md
          file_pattern: README.md
          branch: ${{ env.BRANCH }}
          commit_options: '--no-verify --signoff'
#          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
#          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
#          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
