name: create-release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:

    runs-on: ubuntu-18.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: download and extract latest miner-tools release
        run: |
          PMG_OPENCL_URL="https://github.com/tontechio/pow-miner-gpu/releases/latest/download/minertools-opencl-ubuntu-18.04-x86-64.tar.gz"
          PMG_CUDA_URL="https://github.com/tontechio/pow-miner-gpu/releases/latest/download/minertools-cuda-ubuntu-18.04-x86-64.tar.gz"
          wget -O minertools-opencl-ubuntu-18.04-x86-64.tar.gz $PMG_OPENCL_URL
          wget -O minertools-cuda-ubuntu-18.04-x86-64.tar.gz $PMG_CUDA_URL
          tar -xf minertools-opencl-ubuntu-18.04-x86-64.tar.gz -C ./assets/
          tar -xf minertools-cuda-ubuntu-18.04-x86-64.tar.gz -C ./assets/
          rm -f minertools-opencl-ubuntu-18.04-x86-64.tar.gz
          rm -f minertools-cuda-ubuntu-18.04-x86-64.tar.gz

      - name: download latest blockchain config
        run: |
          BLOCK_CHAIN_GC_URL="https://newton-blockchain.github.io/global.config.json"
          wget -O ./config/global.config.json $BLOCK_CHAIN_GC_URL

      - name: define modes for files
        run: |
          chmod +x ./assets/pow-miner-opencl
          chmod +x ./assets/tonlib-opencl-cli
          chmod +x ./assets/pow-miner-cuda
          chmod +x ./assets/tonlib-cuda-cli
          chmod +x ./assets/lite-client

      - name: prepare cuda assets
        run: |
          GENERAL="README.md ./config/global.config.json ./h-config.sh ./h-manifest.conf ./h-run.sh ./h-stats.sh ./assets/tonminer.service"
          CUDA="./assets/lite-client ./assets/pow-miner-cuda ./assets/tonlib-cuda-cli"
          mkdir tonminer_cuda_hiveos_0.6
          cp --parents $GENERAL $CUDA ./tonminer_cuda_hiveos_0.6/
          tar -zcf tonminer_cuda_hiveos_0.6.tar.gz ./tonminer_cuda_hiveos_0.6

      - name: opencl variable substitution
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "cuda"
          replace: "opencl"
          regex: false
          include: "**h-config.sh"

      - name: prepare opencl assets
        run: |
          GENERAL="README.md ./config/global.config.json ./h-config.sh ./h-manifest.conf ./h-run.sh ./h-stats.sh ./assets/tonminer.service"
          OPENCL="./assets/lite-client ./assets/pow-miner-opencl ./assets/tonlib-opencl-cli"
          mkdir tonminer_opencl_hiveos_0.6
          cp --parents $GENERAL $OPENCL ./tonminer_opencl_hiveos_0.6/
          tar -zcf tonminer_opencl_hiveos_0.6.tar.gz ./tonminer_opencl_hiveos_0.6

      - name: packing
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: tonminer_*_hiveos_0.6.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

